name: Firebase Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2

      - name: Install Dependencies
        working-directory: ./frontend
        run: |
          rm -rf node_modules
          rm -rf node_modules/.cache
          npm install

      - name: Build
        working-directory: ./frontend
        env:
          CI: false
        run: npm run build

      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: frontend/build

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.2

      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: build
          path: frontend/build

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project ${{ secrets.FIREBASE_PROJECT_ID }} --config frontend/firebase.json
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}



